Class = require 'lib/class'
require 'maquina_estados'
require 'estados'
require 'jugador'
require 'hud'
require 'eventos'
require 'enemigos/enemigo'
require 'enemigos/caballero'
require 'enemigos/samurai'